[buildPlans.iosevka-round]
family = "Iosevka Round"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-round.variants.design]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifless"
capital-j = "serifless"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "detached-bend-tailed"
capital-r = "curly-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "curly-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "single-storey-earless-rounded-serifless"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "serifless"
g = "single-storey-earless-rounded"
h = "straight-serifless"
i = "serifless"
j = "serifless"
k = "curly-serifless"
l = "tailed"
m = "earless-rounded-double-arch-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "curly-serifless"
w = "curly-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "curly-serifless"
long-s = "bent-hook-serifless"
eszet = "sulzbacher-descending-serifless"
capital-lambda = "curly-serifless"
lower-alpha = "crossing"
capital-gamma = "serifless"
cyrl-capital-ze = "serifless"
cyrl-ze = "serifless"
lower-iota = "serifed-flat-tailed"
lower-lambda = "straight"
cyrl-capital-ka = "symmetric-touching-serifless"
cyrl-capital-u = "straight-serifless"
zero = "slashed"
one = "no-base"
two = "curly-neck"
three = "two-arcs"
four = "closed"
five = "upright-flat"
six = "straight-bar"
seven = "straight-serifless"
eight = "two-circles"
nine = "straight-bar"
tilde = "low"
asterisk = "turn-hex-high"
underscore = "high"
pilcrow = "high"
caret = "medium"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "et-toothless-rounded"
at = "threefold"
dollar = "open"
cent = "open"
percent = "rings-segmented-slash"
bar = "natural-slope"
lig-ltgteq = "slanted"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"

[buildPlans.iosevka-round.variants.italic]
f = "flat-hook-tailed"
eszet = "sulzbacher-tailed-serifless"

[buildPlans.iosevka-round.variants.oblique]
f = "flat-hook-tailed"
eszet = "sulzbacher-tailed-serifless"

[buildPlans.iosevka-round.ligations]
inherits = "dlig"

[buildPlans.iosevka-round.widths.normal]
shape = 500
menu  = 5
css   = "normal"

[buildPlans.iosevka-round.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevka-round.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-round.weights.medium]
shape = 500
menu  = 500
css   = 500

[buildPlans.iosevka-round.weights.semibold]
shape = 600
menu  = 600
css   = 600

[buildPlans.iosevka-round.weights.bold]
shape = 700
menu  = 700
css   = 700

[buildPlans.iosevkara]
family = "iosevkara"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.iosevkara.variants.design]
capital-a = "curly-serifless"
capital-b = "more-asymmetric-serifless"
capital-c = "serifless"
capital-d = "more-rounded-serifless"
capital-e = "serifless"
capital-f = "serifless"
capital-g = "toothless-rounded-serifless-hooked"
capital-h = "serifless"
capital-i = "serifless"
capital-j = "serifless"
capital-k = "curly-serifless"
capital-l = "serifless"
capital-m = "hanging-serifless"
capital-n = "standard-serifless"
capital-p = "closed-serifless"
capital-q = "detached-bend-tailed"
capital-r = "curly-serifless"
capital-s = "serifless"
capital-t = "serifless"
capital-u = "toothless-rounded-serifless"
capital-v = "curly-serifless"
capital-w = "curly-serifless"
capital-x = "curly-serifless"
capital-y = "curly-serifless"
capital-z = "curly-serifless"
a = "single-storey-earless-rounded-serifless"
b = "toothless-rounded-serifless"
c = "serifless"
d = "toothless-rounded-serifless"
e = "rounded"
f = "serifless"
g = "single-storey-earless-rounded"
h = "straight-serifless"
i = "serifless"
j = "serifless"
k = "curly-serifless"
l = "tailed"
m = "earless-rounded-double-arch-serifless"
n = "earless-rounded-straight-serifless"
p = "earless-rounded-serifless"
q = "earless-rounded-straight-serifless"
r = "earless-rounded-serifless"
s = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
v = "curly-serifless"
w = "curly-serifless"
x = "curly-serifless"
y = "cursive-serifless"
z = "curly-serifless"
long-s = "bent-hook-serifless"
eszet = "sulzbacher-descending-serifless"
capital-lambda = "curly-serifless"
lower-alpha = "crossing"
capital-gamma = "serifless"
lower-iota = "serifed-flat-tailed"
lower-lambda = "straight"
cyrl-capital-ze = "serifless"
cyrl-ze = "serifless"
cyrl-capital-ka = "symmetric-touching-serifless"
cyrl-capital-u = "straight-serifless"
zero = "slashed"
one = "no-base"
two = "curly-neck"
three = "two-arcs"
four = "closed"
five = "upright-flat"
six = "straight-bar"
seven = "straight-serifless"
eight = "two-circles"
nine = "straight-bar"
tilde = "low"
asterisk = "turn-hex-high"
underscore = "high"
caret = "medium"
paren = "normal"
brace = "straight"
number-sign = "upright"
ampersand = "et-toothless-rounded"
at = "threefold"
dollar = "open"
percent = "rings-segmented-slash"
bar = "natural-slope"
ascii-single-quote = "straight"
ascii-grave = "straight"
question = "smooth"
pilcrow = "high"
cent = "open"
lig-ltgteq = "slanted"

[buildPlans.iosevkara.variants.italic]
capital-q = "detached-bend-tailed"
capital-v = "straight-serifless"
a = "single-storey-earless-rounded-tailed"
d = "tailed-serifless"
e = "rounded"
f = "flat-hook-tailed"
h = "tailed-serifless"
i = "tailed-serifed"
j = "serifed"
k = "cursive-bottom-right-serifed"
m = "tailed-top-left-serifed"
n = "tailed-motion-serifed"
q = "earless-rounded-tailed-serifless"
r = "earless-rounded-serifless"
u = "tailed-motion-serifed"
v = "cursive-serifed"
w = "cursive-serifed"
z = "cursive"
five = "oblique-flat"

[buildPlans.iosevkara.variants.oblique]
capital-q = "detached-bend-tailed"
capital-v = "straight-serifless"
a = "single-storey-earless-rounded-tailed"
d = "tailed-serifless"
e = "rounded"
f = "flat-hook-tailed"
h = "tailed-serifless"
i = "tailed-serifed"
j = "serifed"
k = "cursive-bottom-right-serifed"
m = "tailed-top-left-serifed"
n = "tailed-motion-serifed"
q = "earless-rounded-tailed-serifless"
r = "earless-rounded-serifless"
u = "tailed-motion-serifed"
v = "cursive-serifed"
w = "cursive-serifed"
z = "cursive"
five = "oblique-flat"

[buildPlans.iosevkara.ligations]
inherits = "dlig"

[buildPlans.iosevkara.widths.normal]
shape = 500
menu  = 5
css   = "normal"

[buildPlans.iosevkara.weights.light]
shape = 300
menu  = 300
css   = 300

[buildPlans.iosevkara.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevkara.weights.medium]
shape = 500
menu  = 500
css   = 500

[buildPlans.iosevkara.weights.semibold]
shape = 600
menu  = 600
css   = 600

[buildPlans.iosevkara.weights.bold]
shape = 700
menu  = 700
css   = 700